const  confirmUserName = "selfcare/org/confirmUserName";
const  sendOTP = "selfcare/org/sendOTP";
const  verifyOTP = "selfcare/org/verifyOTP";
const  getSubscriptionList = "selfcare/subscription/getSubscriptionList";
const  getOrgNoByActId = "selfcare/subsrestversion/getOrgNoByActId?subsid=";
const  getHelpdeskUrl = "selfcare/helpdesk/helpdeskUrl";
const  getHelpdeskCredentials = "selfcare/helpdesk/getHelpdeskCredentials?roleName=";
const  getHelpdeskTicketList = "rest/api/selfacre/ticket";
const  registration = "selfcare/org/registerSelfCare";